apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: azrulhasni/depositaccount
      context: ../DepositAccount
      jib: {}
    - image: azrulhasni/gateway_kafka
      context: ../Gateway-Kafka
      jib: {}
    - image: azrulhasni/transaction
      context: ../Transaction
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
