version: '2'
services:
  depositaccount-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/DepositAccount/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=DepositAccount
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
