apiVersion: v1
kind: Service
metadata:
  name: gateway_kafka
  namespace: default
  labels:
    app: gateway_kafka
spec:
  selector:
    app: gateway_kafka
  type: NodePort
  ports:
    - name: http
      port: 8080
