apiVersion: v1
kind: Service
metadata:
  name: gatewaykafka
  namespace: default
  labels:
    app: gatewaykafka
spec:
  selector:
    app: gatewaykafka
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
